// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4qvJbeFtwD2HKycfbwWRF91auIID6Hs4',
    appId: '1:952845266913:web:c9cfcf3b1657fa72146ca0',
    messagingSenderId: '952845266913',
    projectId: 'rental-car-app-8b9be',
    authDomain: 'rental-car-app-8b9be.firebaseapp.com',
    storageBucket: 'rental-car-app-8b9be.appspot.com',
    measurementId: 'G-E41HV6WD1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUJGZlUGIu6LafSHhtnciq7EyEFZwNthA',
    appId: '1:952845266913:android:880dcf950a73fe83146ca0',
    messagingSenderId: '952845266913',
    projectId: 'rental-car-app-8b9be',
    storageBucket: 'rental-car-app-8b9be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNCsj31Q0fEkcfI7AdaM18HykH7qOfrg8',
    appId: '1:952845266913:ios:e105cca4bbca270c146ca0',
    messagingSenderId: '952845266913',
    projectId: 'rental-car-app-8b9be',
    storageBucket: 'rental-car-app-8b9be.appspot.com',
    iosBundleId: 'com.example.rentalCarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNCsj31Q0fEkcfI7AdaM18HykH7qOfrg8',
    appId: '1:952845266913:ios:e105cca4bbca270c146ca0',
    messagingSenderId: '952845266913',
    projectId: 'rental-car-app-8b9be',
    storageBucket: 'rental-car-app-8b9be.appspot.com',
    iosBundleId: 'com.example.rentalCarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4qvJbeFtwD2HKycfbwWRF91auIID6Hs4',
    appId: '1:952845266913:web:2fbf5f12d9b4a1df146ca0',
    messagingSenderId: '952845266913',
    projectId: 'rental-car-app-8b9be',
    authDomain: 'rental-car-app-8b9be.firebaseapp.com',
    storageBucket: 'rental-car-app-8b9be.appspot.com',
    measurementId: 'G-1FBELMJWFJ',
  );

}